# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mnet_sync.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Mnet_sync.proto',
  package='Mnetsync',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fMnet_sync.proto\x12\x08Mnetsync\"_\n\rAccountUpdate\x12\x13\n\x0b\x46romBalance\x18\x01 \x01(\x05\x12\x11\n\tToBalance\x18\x02 \x01(\x05\x12\x13\n\x0b\x46romAddress\x18\x03 \x01(\t\x12\x11\n\tToAddress\x18\x04 \x01(\t\"h\n\x12TransactionRequest\x12,\n\x0bTransaction\x18\x01 \x01(\x0b\x32\x17.Mnetsync.AccountUpdate\x12\x11\n\tSignature\x18\x02 \x01(\x0c\x12\x11\n\tTimestamp\x18\x03 \x01(\x05\"G\n\x11TransactionStatus\x12\x0e\n\x06Status\x18\x01 \x01(\t\x12\x11\n\tTimestamp\x18\x02 \x01(\x05\x12\x0f\n\x07\x44\x65tails\x18\x03 \x01(\t\"\x1d\n\nPeerDemand\x12\x0f\n\x07HowMany\x18\x01 \x01(\x05\"S\n\x08PeerInfo\x12\x0c\n\x04Ipv4\x18\x01 \x01(\x05\x12\x0c\n\x04Ipv6\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04Port\x18\x04 \x01(\x05\x12\x0f\n\x07\x41\x64\x64ress\x18\x05 \x01(\t\"7\n\x0fTrustedPeerList\x12$\n\x08PeerList\x18\x01 \x03(\x0b\x32\x12.Mnetsync.PeerInfo\"=\n\x0b\x41\x63\x63ountInfo\x12\x16\n\x0e\x41\x63\x63ountAddress\x18\x01 \x01(\t\x12\x16\n\x0e\x41\x63\x63ountBalance\x18\x02 \x01(\x05\"\'\n\rAccountDemand\x12\x16\n\x0e\x41\x63\x63ountAddress\x18\x01 \x01(\t2\xe2\x01\n\x08Mnetsync\x12=\n\x08GetPeers\x12\x14.Mnetsync.PeerDemand\x1a\x19.Mnetsync.TrustedPeerList\"\x00\x12\x42\n\x0eGetAccountInfo\x12\x17.Mnetsync.AccountDemand\x1a\x15.Mnetsync.AccountInfo\"\x00\x12S\n\x12ProcessTransaction\x12\x1c.Mnetsync.TransactionRequest\x1a\x1b.Mnetsync.TransactionStatus\"\x00\x30\x01\x62\x06proto3')
)




_ACCOUNTUPDATE = _descriptor.Descriptor(
  name='AccountUpdate',
  full_name='Mnetsync.AccountUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FromBalance', full_name='Mnetsync.AccountUpdate.FromBalance', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ToBalance', full_name='Mnetsync.AccountUpdate.ToBalance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FromAddress', full_name='Mnetsync.AccountUpdate.FromAddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ToAddress', full_name='Mnetsync.AccountUpdate.ToAddress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=124,
)


_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='Mnetsync.TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Transaction', full_name='Mnetsync.TransactionRequest.Transaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='Mnetsync.TransactionRequest.Signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='Mnetsync.TransactionRequest.Timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=230,
)


_TRANSACTIONSTATUS = _descriptor.Descriptor(
  name='TransactionStatus',
  full_name='Mnetsync.TransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='Mnetsync.TransactionStatus.Status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='Mnetsync.TransactionStatus.Timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Details', full_name='Mnetsync.TransactionStatus.Details', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=303,
)


_PEERDEMAND = _descriptor.Descriptor(
  name='PeerDemand',
  full_name='Mnetsync.PeerDemand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='HowMany', full_name='Mnetsync.PeerDemand.HowMany', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=334,
)


_PEERINFO = _descriptor.Descriptor(
  name='PeerInfo',
  full_name='Mnetsync.PeerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ipv4', full_name='Mnetsync.PeerInfo.Ipv4', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ipv6', full_name='Mnetsync.PeerInfo.Ipv6', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='Mnetsync.PeerInfo.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Port', full_name='Mnetsync.PeerInfo.Port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Address', full_name='Mnetsync.PeerInfo.Address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=419,
)


_TRUSTEDPEERLIST = _descriptor.Descriptor(
  name='TrustedPeerList',
  full_name='Mnetsync.TrustedPeerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PeerList', full_name='Mnetsync.TrustedPeerList.PeerList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=476,
)


_ACCOUNTINFO = _descriptor.Descriptor(
  name='AccountInfo',
  full_name='Mnetsync.AccountInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountAddress', full_name='Mnetsync.AccountInfo.AccountAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AccountBalance', full_name='Mnetsync.AccountInfo.AccountBalance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=539,
)


_ACCOUNTDEMAND = _descriptor.Descriptor(
  name='AccountDemand',
  full_name='Mnetsync.AccountDemand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountAddress', full_name='Mnetsync.AccountDemand.AccountAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=580,
)

_TRANSACTIONREQUEST.fields_by_name['Transaction'].message_type = _ACCOUNTUPDATE
_TRUSTEDPEERLIST.fields_by_name['PeerList'].message_type = _PEERINFO
DESCRIPTOR.message_types_by_name['AccountUpdate'] = _ACCOUNTUPDATE
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['TransactionStatus'] = _TRANSACTIONSTATUS
DESCRIPTOR.message_types_by_name['PeerDemand'] = _PEERDEMAND
DESCRIPTOR.message_types_by_name['PeerInfo'] = _PEERINFO
DESCRIPTOR.message_types_by_name['TrustedPeerList'] = _TRUSTEDPEERLIST
DESCRIPTOR.message_types_by_name['AccountInfo'] = _ACCOUNTINFO
DESCRIPTOR.message_types_by_name['AccountDemand'] = _ACCOUNTDEMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountUpdate = _reflection.GeneratedProtocolMessageType('AccountUpdate', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTUPDATE,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.AccountUpdate)
  ))
_sym_db.RegisterMessage(AccountUpdate)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONREQUEST,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.TransactionRequest)
  ))
_sym_db.RegisterMessage(TransactionRequest)

TransactionStatus = _reflection.GeneratedProtocolMessageType('TransactionStatus', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONSTATUS,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.TransactionStatus)
  ))
_sym_db.RegisterMessage(TransactionStatus)

PeerDemand = _reflection.GeneratedProtocolMessageType('PeerDemand', (_message.Message,), dict(
  DESCRIPTOR = _PEERDEMAND,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.PeerDemand)
  ))
_sym_db.RegisterMessage(PeerDemand)

PeerInfo = _reflection.GeneratedProtocolMessageType('PeerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PEERINFO,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.PeerInfo)
  ))
_sym_db.RegisterMessage(PeerInfo)

TrustedPeerList = _reflection.GeneratedProtocolMessageType('TrustedPeerList', (_message.Message,), dict(
  DESCRIPTOR = _TRUSTEDPEERLIST,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.TrustedPeerList)
  ))
_sym_db.RegisterMessage(TrustedPeerList)

AccountInfo = _reflection.GeneratedProtocolMessageType('AccountInfo', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTINFO,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.AccountInfo)
  ))
_sym_db.RegisterMessage(AccountInfo)

AccountDemand = _reflection.GeneratedProtocolMessageType('AccountDemand', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTDEMAND,
  __module__ = 'Mnet_sync_pb2'
  # @@protoc_insertion_point(class_scope:Mnetsync.AccountDemand)
  ))
_sym_db.RegisterMessage(AccountDemand)



_MNETSYNC = _descriptor.ServiceDescriptor(
  name='Mnetsync',
  full_name='Mnetsync.Mnetsync',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=583,
  serialized_end=809,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPeers',
    full_name='Mnetsync.Mnetsync.GetPeers',
    index=0,
    containing_service=None,
    input_type=_PEERDEMAND,
    output_type=_TRUSTEDPEERLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccountInfo',
    full_name='Mnetsync.Mnetsync.GetAccountInfo',
    index=1,
    containing_service=None,
    input_type=_ACCOUNTDEMAND,
    output_type=_ACCOUNTINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessTransaction',
    full_name='Mnetsync.Mnetsync.ProcessTransaction',
    index=2,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MNETSYNC)

DESCRIPTOR.services_by_name['Mnetsync'] = _MNETSYNC

# @@protoc_insertion_point(module_scope)
